title: Iulia's Tech Stuff
head_title: Tech Stuff
description: Blogs, Tutorials, Videos, Meetups, Conferences and all things tech
author: Iulia Feroli
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
